### ISSUE TITLE
Secure Login (Base64 Authentication) 

### ISSUE THREAD

**Issue by nakraft** [nakraft/tracker4J#4]
## Overview 
Secure Login (Base64 Authentication) . This would increase security and make it so that job applications are confidential. 

## Implementation Ideas
We could consider adding in 'guest' users that could log into support your profile. For example, career coaches or people who you have asked to write you recommendations or to review your application materials.

**Comment by Parth-25m** [comment]
Completed in https://github.com/nakraft/tracker4J/pull/22
![base64](https://user-images.githubusercontent.com/22641752/205519760-0c615342-5714-44d3-8dde-92af69396bfd.png)
