### ISSUE TITLE
Option to link third party career fairs to user profile

### ISSUE THREAD

**Issue by nakraft** [nakraft/tracker4J#5]
## Overview 
Option to link third party career fairs to user profile.

**Comment by Parth-25m** [comment]
# Add career fair option is now available in Saved Jobs Tab
![cf1](https://user-images.githubusercontent.com/22641752/205514859-59343b5e-666d-4b5a-b2bb-6a8076205efd.png)

# Career Fair pop up, requires name, URL and date to be filled.
![cf2](https://user-images.githubusercontent.com/22641752/205514860-f0927543-038c-4c10-82ed-e5183f4ac3ce.png)

# Stored in mongodb database
![cf3](https://user-images.githubusercontent.com/22641752/205514861-5e6f8d54-1122-47c5-b2bd-490e4605870e.png)

**Comment by nakraft** [comment]
This looks great! I will make sure to update the statistics dashboard with statistics about the number of career fairs one has logged as well.
